### ISSUE TITLE
Using two scalebreaker dialogs

### ISSUE THREAD

**Issue by daonsh** [salsita/jquery-ui-scalebreaker#5]
Hi, I'm trying to use two scalebreaker dialogs in one page.
I want one at the top to be like a toolbar (I changed the code a bit to make it stay forever) and at the bottom for messages to the user.
I create two divs and try to assign each one a scalebreaker:
The problem is that the second scalebreaker does not behave well, it does not move appropriately. It stays in a constant place.
I think it may has to do with that they have the same idNamespace, but as I read here it's problematic to change it. Would love to have an idea for a quick fix for this.

Example follows:
..
..
..

<p>Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb.</p>

<p>Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass.</p>

<a class="click-me-message" href="#">show scalebreaker</a>
  

<div id='headerdiv'>  
  </div>
  
<div id='footerdiv'>  
</div>

<script>
    $(document).ready(function(){

       // just create two instead of one as in the example, and not attached to 
       // body but to their own div.
        $('#headerdiv').scalebreaker({
            dialogContent: "<p>I am toolbar.</p>",
            dialogPosition: 'top',
            debug: true,
            cssAnimated: false,
            dialogPosition: 'top',
            showCloseButton : false,
            closeOnBackdrop : false
          
        })
        $('.click-me').on('click', function(e){
            e.preventDefault();
            $('#headerdiv').scalebreaker('show');
        })
        
        $('#footerdiv').scalebreaker({
            dialogContent: "<p>I am a message below.</p>",
            dialogPosition: 'bottom',
            debug: true,
            cssAnimated: true,            
            showCloseButton : true,
            closeOnBackdrop : true          
        })
        $('.click-me-message').on('click', function(e){
            e.preventDefault();
            $('#footerdiv').scalebreaker('show');
        })
    })
</script>

Thanks

**Comment by ghost** [comment]
Hello @shaulid,

I haven't really tuned the plugin to work with multiple dialog instances at the same time, rather just added features to replace the content and keep in a single instance. I guess the main issue is that the scalebreaker elements use an ID and querying for that will only return the first instance found in the DOM, which would result in the behavior you describe.

If you want to try to fix it, I imagine the fastest way would be to change the `id`s to `class`es where the elements are prepared:

```
@rawElement =
        "<div class='#{@options.idNamespace}-wrapper'>
          <div class='#{@options.idNamespace}-dialog-scalable'>
            <div class='#{@options.idNamespace}-dialog-scrollable'>
              <div class='#{@options.idNamespace}-dialog-content'></div>"

      if @options.showCloseButton
        @rawElement += "      <span class='#{@options.idNamespace}-dialog-close'></span>"

      @rawElement += "    </div>
          </div>
        </div>"
```

And then also change the references:

```
@wrapper = $('.' + @options.idNamespace + '-wrapper')
@dialog = $('.' + @options.idNamespace + '-dialog-scalable')
@scrollarea = $('.' + @options.idNamespace + '-dialog-scrollable')
@content = $('.' + @options.idNamespace + '-dialog-content')
@close = $('.' + @options.idNamespace + '-dialog-close')
```

You will also have to change the CSS to point to the classes rather than the ids.

This way the code should start working with all instances, but you will likely encounter problems like the close functionality closing both dialogs at the same time or similar. The plugin would have to be rewritten a bit more to work with multiple instances flawlessly. Hope this helps.

**Comment by daonsh** [comment]
Hi,

Thank you very much for the detailed response!
I will look into it and see whether it's something I can do myself.

Anyhow, thanks for the plugin!
